const DEFAULT_COUNT = 4;
const MAX_COUNT = 8;

const PRESETS = {
  home: {
    title: "Inicio",
    cardCount: 3,
    showHero: true,
    showTabs: false,
    showTopAction: false,
    showFooterButton: false,
    showFloatingAction: true,
    showMap: false,
    showInfoCard: false,
    showForm: false,
  },
  "mis-rutas": {
    title: "Mis rutas",
    cardCount: 5,
    showHero: false,
    showTabs: false,
    showTopAction: false,
    showFooterButton: true,
    showFloatingAction: false,
    showMap: false,
    showInfoCard: false,
    showForm: false,
  },
  "mis-tareas": {
    title: "Mis tareas",
    cardCount: 4,
    showHero: false,
    showTabs: true,
    showTopAction: false,
    showFooterButton: true,
    showFloatingAction: false,
    showMap: false,
    showInfoCard: false,
    showForm: false,
  },
  registros: {
    title: "Registros",
    cardCount: 4,
    showHero: false,
    showTabs: false,
    showTopAction: true,
    showFooterButton: true,
    showFloatingAction: false,
    showMap: false,
    showInfoCard: false,
    showForm: false,
  },
  "route-map": {
    title: "Zona mapa",
    cardCount: 3,
    showHero: false,
    showTabs: false,
    showTopAction: false,
    showFooterButton: false,
    showFloatingAction: false,
    showMap: true,
    showInfoCard: true,
    showForm: false,
  },
  "zona-list": {
    title: "Pendientes",
    cardCount: 5,
    showHero: false,
    showTabs: false,
    showTopAction: false,
    showFooterButton: true,
    showFloatingAction: false,
    showMap: false,
    showInfoCard: false,
    showForm: false,
  },
  "product-list": {
    title: "Establecimiento detalle",
    cardCount: 4,
    showHero: false,
    showTabs: false,
    showTopAction: false,
    showFooterButton: true,
    showFloatingAction: false,
    showMap: false,
    showInfoCard: true,
    showForm: false,
  },
  "registro-form": {
    title: "Registro",
    cardCount: 6,
    showHero: false,
    showTabs: false,
    showTopAction: false,
    showFooterButton: true,
    showFloatingAction: false,
    showMap: false,
    showInfoCard: false,
    showForm: true,
  },
  profile: {
    title: "Mi perfil",
    cardCount: 5,
    showHero: false,
    showTabs: false,
    showTopAction: false,
    showFooterButton: false,
    showFloatingAction: false,
    showMap: false,
    showInfoCard: false,
    showForm: true,
  },
  login: {
    title: "Ingresar",
    cardCount: 4,
    showHero: true,
    showTabs: false,
    showTopAction: false,
    showFooterButton: false,
    showFloatingAction: false,
    showMap: false,
    showInfoCard: false,
    showForm: true,
  },
};

export function getLoadingItems(count, { fallback = DEFAULT_COUNT, max = MAX_COUNT } = {}) {
  const normalized = Number.isFinite(count) ? Math.trunc(count) : fallback;
  const safeCount = normalized >= 1 ? Math.min(normalized, max) : fallback;
  return Array.from({ length: safeCount }, (_, index) => index);
}

export function getLoadingPreset(name) {
  return PRESETS[name] ?? PRESETS["mis-rutas"];
}
